version: "3.8"
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: competition
      MYSQL_USER: dev2025
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin:5.2.2-fpm-alpine
    restart: always
    ports:
      - 8080:80
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - 3000:80
    depends_on:
      - db

volumes:
  data:
